In [3]:
#Assignment 1 - Working with NumPy
#Step 1 Install NumPy using
!pip install numpy


In [8]:
import numpy as np

# Create a 1D NumPy array with integers from 1 to 20
arr = np.arange(1,21)
print(arr)

# a. Calculate sum, mean, median, and standard deviation
sum_val = np.sum(arr)
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev_val = np.std(arr)

print("Sum:", sum_val)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev_val)

# b. Find indices of elements greater than 10
ind_gt_10 = np.where(arr>10)[0]
print("Indices of elements > 10:", ind_gt_10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


In [12]:
import numpy as np

# a. Create a 2D array (4x4) with values from 1 to 16
arr_2d = np.arange(1,17).reshape(4,4)
print("Original 4x4 Array:\n", arr_2d)

# b. Transpose the array
t_arr = arr_2d.T
print("Transpose 4x4 Array:\n", t_arr)

# c. Row-wise sum & column-wise sum
r_sum = np.sum(arr_2d, axis = 1)
print("Row-wise sum:",r_sum)

c_sum = np.sum(arr_2d, axis = 0)
print("Column-wise sum:",r_sum)


Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose 4x4 Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [10 26 42 58]


In [22]:
import numpy as np

np.random.seed(0)

# Create two random 3x3 arrays with integers from 1 to 20
A = np.random.randint(1,21, size = (3,3))
B = np.random.randint(1,21, size = (3,3))

print("Array A:\n", A)
print("Array B:\n", B)

# a. Element-wise operations
add = A+B
sub = A-B
mul = A*B

print("\nElement-wise Addition:\n", add)
print("\nElement-wise Subtraction:\n", sub)
print("\nElement-wise Multiplication:\n", mul)

# b. Dot product
dot_prod = np.dot(A, B)
print("\nDot Product of A and B:\n", dot_prod)

Array A:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]
Array B:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]

Element-wise Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]

Element-wise Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]

Element-wise Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]

Dot Product of A and B:
 [[112 221 303]
 [148 200 132]
 [375 552 404]]


In [26]:
import numpy as np

arr_1d = np.arange(1,13)
print("Original 1D array:\n", arr_1d)

arr_2d = arr_1d.reshape(3,4)
print("Reshaped array:\n", arr_2d)

sl = arr_2d[0:2,2:4] #arr_2d[:2, -2:]
print("\nSliced (First 2 Rows, Last 2 Columns):\n", sl)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced (First 2 Rows, Last 2 Columns):
 [[3 4]
 [7 8]]
